# Generated by Django 4.2.9 on 2024-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denomination_etablissement', models.CharField(max_length=3000, null=True)),
                ('Code', models.CharField(max_length=3000, null=True)),
                ('Nom_et_prenom_du_directeur', models.CharField(max_length=3000, null=True)),
                ('Nom_et_prenom_du_fondateur', models.CharField(max_length=3000, null=True)),
                ('Nombre_enseignants', models.CharField(max_length=3000, null=True)),
                ('Cycle', models.CharField(max_length=3000, null=True)),
                ('Localisation', models.CharField(max_length=3000, null=True)),
                ('Drena', models.CharField(max_length=3000, null=True)),
                ('Contacts', models.CharField(max_length=3000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
            },
        ),
    ]
