# Generated by Django 4.2.9 on 2024-02-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaire',
            old_name='Nom_et_prenom_du_directeur',
            new_name='Nom_prenom_directeur',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='Nom_et_prenom_du_fondateur',
            new_name='Nom_prenom_fondateur',
        ),
    ]
