# Generated by Django 4.2.9 on 2024-02-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_rename_nom_et_prenom_du_directeur_formulaire_nom_prenom_directeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='Nombre_enseignants',
            field=models.IntegerField(max_length=3000, null=True),
        ),
    ]
