# Generated by Django 4.2.9 on 2024-02-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_alter_formulaire_nombre_enseignants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='Cycle',
            field=models.CharField(choices=[('Premier Cycle', 'Premier Cycle'), ('Second Cycle', 'Second Cycle'), ('Cycle Superieur', 'Cycle Superieur')], max_length=3000, null=True),
        ),
    ]
