# Generated by Django 4.2.9 on 2024-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_naissance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='dernier_diplome',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='emploi_precedent',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='image_diplome',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='image_profil',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='lieu_naissance',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='nombre_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
