# Generated by Django 4.2.9 on 2024-02-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_email_alter_inscription_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
