# Generated by Django 4.2.9 on 2024-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_inscription_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
