# Generated by Django 4.2.9 on 2024-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_remove_inscription_image_diplome_inscription_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='Téléchargements'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='Bureau'),
        ),
    ]
