# Generated by Django 4.2.9 on 2024-02-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_remove_inscription_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='dernier_diplome',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='emploi_precedent',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='fonction',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('Professeure', 'Professeure'), ('Educatrice', 'Educatrice'), ('Educateur', 'Educateur')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='lieu_naissance',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='nombre_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
