# Generated by Django 4.2.9 on 2024-02-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0010_inscription_cv_inscription_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
    ]
