# Generated by Django 4.2.9 on 2024-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_alter_inscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='diplome',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
