# Generated by Django 4.2.9 on 2024-02-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_alter_inscription_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
