# Generated by Django 4.2.9 on 2024-02-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0013_alter_inscription_diplome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='diplome',
        ),
    ]
