# Generated by Django 4.2.9 on 2024-02-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0014_remove_inscription_diplome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='emploi_precedent',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='nombre_experience',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='telephone',
        ),
    ]
