# Generated by Django 4.2.9 on 2024-02-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0016_remove_inscription_dernier_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='fonction',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('Professeure', 'Professeure'), ('Educatrice', 'Educatrice'), ('Educateur', 'Educateur')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='nombre_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
