# Generated by Django 4.2.9 on 2024-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0017_inscription_email_inscription_fonction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
