# Generated by Django 4.2.9 on 2024-02-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0018_alter_inscription_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='telephone',
        ),
    ]
