# Generated by Django 4.2.9 on 2024-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0019_remove_inscription_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='dernier_diplome',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='emploi_precedent',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
