# Generated by Django 4.2.9 on 2024-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0023_remove_inscription_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
