# Generated by Django 4.2.9 on 2024-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0024_inscription_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
