# Generated by Django 4.2.9 on 2024-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0026_alter_inscription_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance',
            field=models.DateTimeField(null=True),
        ),
    ]
