# Generated by Django 4.2.9 on 2024-02-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0027_alter_inscription_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
