# Generated by Django 4.2.9 on 2024-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0030_remove_inscription_datetimeofupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, max_length=3000, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dernier_diplome',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='fonction',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('Professeure', 'Professeure'), ('Educatrice', 'Educatrice'), ('Educateur', 'Educateur')], max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='lieu_naissance',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
