# Generated by Django 4.2.9 on 2024-02-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0031_alter_inscription_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='image_profil',
            new_name='photo_profil',
        ),
    ]
